# holds jobs and steps for Github actions

# whats action is caled
name : Checks

# when action should be called
on: [push]

# What is the action to perform

jobs: 
  test-lint:
    name: Test and Lint
    # Platform to run job on
    runs-on: ubuntu-20.04
    # different things that run for the given job in defined manner like step 1..2..3
    steps: 
      - name: Login to Docker Hub
      # uses are premade actions or we can make our own also
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"


  
  # What we do is when code is pushed we do a job by first loggin in to Docker and then 
  # cheking the code 
  # we then test it using predefined command and then 
  # we lint it using flake8
  # if any step failed the job failed